# Unless filling for special features, all features should fill for previous forks (starting from Frontier) too
stable:
  evm-type: stable
  fill-params: --until=Cancun
  solc: 0.8.21
develop:
  evm-type: develop
  fill-params: --until=Prague
  solc: 0.8.21
pectra-devnet-6:
  evm-type: pectra-devnet-6
  fill-params: --until=Prague
  solc: 0.8.21