name: Build and Package Fixture Release
inputs:
  release_name:
    description: 'Name of the fixture release'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up uv
      uses: ./.github/actions/setup-uv
    - name: Set up Python
      shell: bash    
      run: uv python install 3.10 --no-progress
    - name: Install EEST
      shell: bash
      run: uv sync --no-progress
    - name: Extract fixture release properties from config
      id: properties
      shell: bash
      run: |
        echo "release_name=${{ inputs.release_name }}"
        uv run -q .github/scripts/get_release_props.py ${{ inputs.release_name }} >> "$GITHUB_OUTPUT"
    - uses: ./.github/actions/build-evm-base
      id: evm-builder
      with:
        type: ${{ steps.properties.outputs.evm-type }}
    - name: Wrap ethereum/tests fixtures with eofwrap tool
      shell: bash
      if: ${{ steps.properties.outputs.eofwrap }}
      run: |
        curl -L ${tests_url}${tests_version}.tar.gz | tar -xz
        ls -l
        uv run eofwrap tests-${tests_version}/BlockchainTests/GeneralStateTests/ fixtures_${{ inputs.release_name }}/${output_path}
        mkdir -p ./fixtures_${{ inputs.release_name }}/.meta/
        mv fixtures_${{ inputs.release_name }}/${output_path}/metrics.json ./fixtures_${{ inputs.release_name }}/.meta/eofwrap_metrics.json
      env:
        tests_url: https://github.com/ethereum/tests/archive/refs/tags/v
        tests_version: 14.1
        output_path: blockchain_tests/osaka/eofwrap
    - name: Generate fixtures
      shell: bash
      run: |
        for spec in ${{ steps.properties.outputs.specs }}; do
          echo "Running for $spec TransactionTest"
          echo "CLI: uv run fill -n ${{ steps.evm-builder.outputs.x-dist }} --evm-bin=${{ steps.evm-builder.outputs.evm-bin }} --solc-version=${{ steps.properties.outputs.solc }} --skip-evm-dump ${{ steps.properties.outputs.fill-params }} $spec -m transaction_test"
          uv run fill -n ${{ steps.evm-builder.outputs.x-dist }} \
            --evm-bin=${{ steps.evm-builder.outputs.evm-bin }} \
            --solc-version=${{ steps.properties.outputs.solc }} \
            --skip-evm-dump \
            ${{ steps.properties.outputs.fill-params }} \
            $spec -m transaction_test

          echo "Running for $spec StateTest"
          echo "CLI: uv run fill -n ${{ steps.evm-builder.outputs.x-dist }} --evm-bin=${{ steps.evm-builder.outputs.evm-bin }} --solc-version=${{ steps.properties.outputs.solc }} --skip-evm-dump ${{ steps.properties.outputs.fill-params }} $spec -m state_test"
          uv run fill -n ${{ steps.evm-builder.outputs.x-dist }} \
            --evm-bin=${{ steps.evm-builder.outputs.evm-bin }} \
            --solc-version=${{ steps.properties.outputs.solc }} \
            --skip-evm-dump \
            ${{ steps.properties.outputs.fill-params }} \
            $spec -m state_test

          echo "Running for $spec BlockchainTest"
          echo "CLI: uv run fill -n ${{ steps.evm-builder.outputs.x-dist }} --evm-bin=${{ steps.evm-builder.outputs.evm-bin }} --solc-version=${{ steps.properties.outputs.solc }} --skip-evm-dump ${{ steps.properties.outputs.fill-params }} $spec -m blockchain_test"
          uv run fill -n ${{ steps.evm-builder.outputs.x-dist }} \
            --evm-bin=${{ steps.evm-builder.outputs.evm-bin }} \
            --solc-version=${{ steps.properties.outputs.solc }} \
            --skip-evm-dump \
            ${{ steps.properties.outputs.fill-params }} \
            $spec -m blockchain_test
        done
    - name: Compress fixtures
      shell: bash
      run: |
        tar -czvf fixtures_${{ inputs.release_name }}.tar.gz fixtures
    - uses: actions/upload-artifact@v4
      with:
        name: fixtures_${{ inputs.release_name }}
        path: fixtures_${{ inputs.release_name }}.tar.gz
